name: go_play_bloc
description: Share Code between Flutter Mobile and Web
version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.7
  equatable: ^1.1.1
  http: ^0.12.0+4
  bloc: ^4.0.0
  flutter_bloc: ^4.0.0
